# -------------------------------------------------------
# Copyright (c) [2024] FASNY
# All rights reserved
# -------------------------------------------------------
# Automatic invoices processing
# -------------------------------------------------------
# Nadège LEMPERIERE, @6th november 2024
# Latest revision: 6th november 2024
# -------------------------------------------------------

name: Invoice Processing Tool Release Check

on:
    push:
        tags:
            - "v[0-9]+.[0-9]+.[0-9]+"

jobs:

    check:
        name: Analyze Package
        runs-on: ubuntu-latest
        container:
          image: docker://python:latest
          options: --entrypoint /bin/bash
        steps:
            - name: Checkout code
              uses: actions/checkout@master

            - name: Installing dependencies
              run: pip install -r requirements-test.txt

            - name: Linting module
              run: pylint process.py

            - name: Run pip-audit to check for vulnerabilities
              run: pip-audit -r requirements.txt --format json